# Build for SEComplexity
version: 2.1

jobs:
  build:
      docker:
        - image: srcml/ubuntu_x86_64_base
      steps:
        - checkout
        - run: apt update
        - run: mkdir /Build
        - run: cd /Build && cmake -DCMAKE_BUILD_TYPE=Release .. -G Ninja
        - run: cd /Build && ninja && ninja install && ldconfig
        - run: cd /Build && ninja run
        - run: cd /Build && cpack -G DEB
        - store_artifacts:
          path: /Build/dist/*.deb
